package syntax.backend.runways.dto

import com.fasterxml.jackson.databind.node.ObjectNode
import syntax.backend.runways.entity.Tag
import java.util.*

data class AutoGeneratedCourseDTO (
    val id : UUID,
    val title: String,
    val distance: Float,
    val position: ObjectNode?,
    val coordinate: ObjectNode?,
    val tag : List<Tag>,
    val sido : String?,
    val sigungu : String?,
)
