package syntax.backend.runways.dto

data class StatusMessageDTO (
    val step: String,        // 예: "STARTED", "PROCESSING", "COMPLETED"
    val message: String,     // 예: "처리를 시작합니다", "답변을 생성 중입니다"
    val llmResponse : List<AutoGeneratedCourseDTO>?
)
